### ISSUE TITLE
게시글 title 디자인 변경 시 몇몇 게시글 적용 오류

### ISSUE THREAD

**Issue by Jeongho0805** [Jeongho0805/portfolio#2]
## 이슈 발생
```css
<style>
    a:link {
        color: black;
        text-decoration: none;
    }
    a:hover {
        color: black;
        text-decoration: underline;
    }
</style>
```

![image](https://user-images.githubusercontent.com/96610382/187560427-6003b09b-fc39-4b6b-ad99-0e13b1579531.png)

</br>

- 다음과 같이 css작성 후 게시판을 보면 몇몇 게시글은 css 적용이 되지 않는 문제가 발생했다.

</br>

## 해결
- 처음에는 paging기능으로 인하여 page에 담긴 모든 content에 css가 정상적으로 적용되지 않는 오류 인줄 알았다.
- 하지만 페이지 소스를 봐도 css는 정상적으로 기재되어 있었다.
- 알고보니 색상 반영이 안된 게시글들은 조회수가 0이 아닌 경우였다.  &rightarrow;  즉 한번 방문한 경우였다.
- 방문한 경우 css에서 default값으로 글씨색을 파란색으로 설정하는것 같았다. 그래서 다음과 같이 수정했다.

```css
<style>
    a:link {
        color: black;
        text-decoration: none;
    }
    a:hover {
        color: black;
        text-decoration: underline;
    }
    a:visited {
        color: black;
        text-decoration: none;
    }
</style>
```

- a: visited 설정을 추가해주니 다음과 같이 정상적으로 게시글 색상이 출력되는걸 볼 수 있다.
</br>

![image](https://user-images.githubusercontent.com/96610382/188143129-e553365f-765b-4da8-b364-e6a37e79031f.png)
